esphome:
  name: rfdoorbell
  friendly_name: RFDoorbell
  includes:
    - cc1101.h
  libraries:
    - SPI
    - "SmartRC-CC1101-Driver-Lib"

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: ERROR


mqtt:
  broker: MQTT IP ADDRESS HERE (NO PORT)

# Enable Home Assistant API
api:
  encryption:
    key: "MAKE A PASSWORD HERE, YOU WILL NEED IT TO ADD TO HOMEASSISTANT"

ota:
  password: "OTA PASSWORD, SET THIS TO SOMETHING RANDOM"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Rfdoorbell Fallback Hotspot"
    password: "SET THIS PASSWORD TO SOMETHING"

captive_portal:


sensor:
  - platform: custom
    lambda: |-
      auto my_sensor = new CC1101(
        18, // SCK
        19, // MISO
        23, // MOSI
        5, // CSN
        12, // GDO0
        200, // bandwidth_in_khz
        433.92 // freq_in_mhz
      );
      App.register_component(my_sensor);
      return {my_sensor};
    sensors:
      id: transciver
      internal: true

remote_receiver:
  - pin: 12 # This is GDO0
      # on the esp8266 use any of D1,D2,D5,D6,D7,Rx
      # Don't use D3,D4,D8,TX, boot often fails.
      # Can't be D0 or GPIO17 b/c no interrupts
    # dump: # uncomment if you need to sniff another signal
    #   - rc_switch
    tolerance: 99%
    filter: 250us
    idle: 4ms
    buffer_size: 2kb

binary_sensor:
  - platform: remote_receiver
    name: Doorbell
    filters:
      - delayed_off: 150ms # if it isnt detecting remove this, doorbell seems to send multiple of the same signal, this makes sure you only get one activation
    rc_switch_raw:
      code: '00010010000101111101000'
      protocol: 1
    on_press:
      then:
        - mqtt.publish: # change this if your not using scrypted, you can delete if you only need a sensor exposed into HomeAssistant
            topic: "scrypted/doorbell/doorbell"
            payload: "OFF"
        - mqtt.publish:
            topic: "scrypted/doorbell/doorbell"
            payload: "ON"
        - mqtt.publish:
            topic: "scrypted/doorbell/doorbell"
            payload: "OFF"




    
